### ISSUE TITLE
python-poppler-glib is not outdated

### ISSUE THREAD

**Issue by medoc92** [cbrunet/python-poppler#14]
This is just a doc comment: your note  on https://cbrunet.github.io/python-poppler/  that the python-poppler poppler-glib binding is outdated is quite misleading:

````
python-poppler
    Binding based on poppler-glib. Latest version is from 2009…
````

This module has not been updated because it is now an integral part of poppler-glib. It works fine with python3, and it's probably the most complete binding. The thing which is actually quite lagging is poppler-cpp (no access to annotations for example, which was my use case, but I guess that there are other things missing).

Because your project comes very early in search results for "python poppler", and because the existence of the poppler-glib binding is not easily discoverable, it would be really helpful if you could update this part of your documentation.

**Comment by cbrunet** [comment]
Thank you for the clarification. I will update the documentation accordingly. However, I will need some help, because I didn't found any reference to this binding in poppler-glib source. Where is-it documented? Why is it no longer included in recent releases of Ubuntu? Why isn't it available on PyPI? How do you mean that it works directly through the glib binding, without the need of a special binding? I must admit I'm not very familiar with glib...

**Comment by cbrunet** [comment]
@medoc92 : Could you please review the paragraph I wrote about poppler-glib binding?

**Comment by medoc92** [comment]
Could you point me to the paragraph you mention above ? Can't find it...

Actually, I am not familiar either with glib, and all my information comes from this post: https://stackoverrun.com/fr/q/2540576 , and the fact that, after installing the gir1.2-poppler-0.18 package on Ubuntu, I can happily insert `from gi.repository import Poppler` in a python3 program, and things just work...

As a C++ programmer, I hate gobject with a passion, but it's clear that their introspection and language bindings functions are without equal. 

And last, I know it's not of your responsibility, but it would be nice if the cpp API would add access to annotations... (esp. to make things simpler on Windows, where I don't really want to go the glib way...)

**Comment by cbrunet** [comment]
Oh, sorry! https://github.com/cbrunet/python-poppler/blob/07d82b64f9ade5041723be1bdd3bb70014cc7bc5/docs/index.rst

I 100% with you. I choose to bind poppler-cpp because it has less dependencies, and I hope to be able to package it with binaries one day.

**Comment by medoc92** [comment]
````
poppler-glib
    Using PyGObject, and instrospection data, you should be able to use the poppler-glib library directly from Python, in a GTK+ 3 environment. No special python binding needed.
````

I'd simplify this, and make it more certain (I can attest that this works...). Maybe something like:

    poppler-glib comes with integral Python bindings generated by the standard gobject introspection tools.

And also maybe, I'd change the description of python-poppler. Instead of just "not updated since 2009", I'd say something like "not needed any more with the current poppler-glib, and not updated since 2009".

There is a doc here which a high level overview of how it works: https://gi.readthedocs.io/en/latest/

**Comment by medoc92** [comment]
Also maybe, if I have some time, I'll submit an update to poppler-cpp for at least minimum support of the annotations interfaces. Except if you have a project in this direction...
