### ISSUE TITLE
Executing tests

### ISSUE THREAD

**Issue by frispete** [cbrunet/python-poppler#19]
Hi,

do you have an idea, how to package pybind11_tests, that your tests require?

Pete

**Comment by cbrunet** [comment]
I'm not sure to understand. pybind11 is used to compile the C++ binding. The tests are all Python... What tests are you talking about?

**Comment by frispete** [comment]
Here's the result of a build with testing enabled:

```[   40s] + PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-poppler-0.2.1-0.x86_64/usr/lib/python3.8/site-packages
[   40s] + PYTHONDONTWRITEBYTECODE=1
[   40s] + pytest-3.8 --ignore=_build.python2 --ignore=_build.python3 --ignore=_build.pypy3 -v
[   41s] ============================= test session starts ==============================
[   41s] platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
[   41s] cachedir: .pytest_cache
[   41s] rootdir: /home/abuild/rpmbuild/BUILD/python-poppler-0.2.1
[   41s] collecting ... Failed to import pybind11_tests from pytest:
[   41s]   ModuleNotFoundError: No module named 'pybind11_tests'
[   41s] collected 0 items / 1 error
[   41s] 
[   41s] ==================================== ERRORS ====================================
[   41s] ________________________ ERROR collecting test session _________________________
[   41s] pybind11/tests/conftest.py:237: in _test_import_pybind11
[   41s]     import pybind11_tests  # noqa: F401 imported but unused
[   41s] E   ModuleNotFoundError: No module named 'pybind11_tests'
[   41s] 
[   41s] During handling of the above exception, another exception occurred:
[   41s] /usr/lib/python3.8/site-packages/py/_path/common.py:383: in visit
[   41s]     for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
[   41s] /usr/lib/python3.8/site-packages/py/_path/common.py:435: in gen
[   41s]     for p in self.gen(subdir):
[   41s] /usr/lib/python3.8/site-packages/py/_path/common.py:424: in gen
[   41s]     dirs = self.optsort([p for p in entries
[   41s] /usr/lib/python3.8/site-packages/py/_path/common.py:425: in <listcomp>
[   41s]     if p.check(dir=1) and (rec is None or rec(p))])
[   41s] /usr/lib/python3.8/site-packages/_pytest/nodes.py:574: in _recurse
[   41s]     ihook = self._gethookproxy(dirpath)
[   41s] /usr/lib/python3.8/site-packages/_pytest/nodes.py:550: in _gethookproxy
[   41s]     my_conftestmodules = pm._getconftestmodules(
[   41s] /usr/lib/python3.8/site-packages/_pytest/config/__init__.py:523: in _getconftestmodules
[   41s]     mod = self._importconftest(conftestpath, importmode)
[   41s] /usr/lib/python3.8/site-packages/_pytest/config/__init__.py:557: in _importconftest
[   41s]     mod = import_path(conftestpath, mode=importmode)
[   41s] /usr/lib/python3.8/site-packages/_pytest/pathlib.py:520: in import_path
[   41s]     importlib.import_module(module_name)
[   41s] /usr/lib64/python3.8/importlib/__init__.py:127: in import_module
[   41s]     return _bootstrap._gcd_import(name[level:], package, level)
[   41s] <frozen importlib._bootstrap>:1014: in _gcd_import
[   41s]     ???
[   41s] <frozen importlib._bootstrap>:991: in _find_and_load
[   41s]     ???
[   41s] <frozen importlib._bootstrap>:975: in _find_and_load_unlocked
[   41s]     ???
[   41s] <frozen importlib._bootstrap>:671: in _load_unlocked
[   41s]     ???
[   41s] /usr/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
[   41s]     exec(co, module.__dict__)
[   41s] pybind11/tests/conftest.py:244: in <module>
[   41s]     _test_import_pybind11()
[   41s] pybind11/tests/conftest.py:241: in _test_import_pybind11
[   41s]     sys.exit(1)
[   41s] E   SystemExit: 1
[   41s] =========================== short test summary info ============================
[   41s] ERROR  - SystemExit: 1
[   41s] !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
[   41s] =============================== 1 error in 0.22s ===============================
[   41s] error: Bad exit status from /var/tmp/rpm-tmp.ByAJj2 (%check)
[   41s] 
```

I can provide a link to full builds later, if you want. (OBS is busy)

**Comment by frispete** [comment]
Full [build log](https://build.opensuse.org/package/live_build_log/home:frispete:python/python-poppler/openSUSE_Tumbleweed/x86_64)

**Comment by cbrunet** [comment]
It looks like you are trying to execute pybind11 tests.  I'm not sure why. Is it something missing in my cmake config?

**Comment by frispete** [comment]
Okay, slowly getting to the bottom of this. It boils down to: pytest should be running with tests/ argument (I was missing that).

Running pytest without arguments finds pybind11/tests, but those fails..

May I kindly ask you to distribute tests/ as well, that would allow packagers to run the self tests during build. We try to do this with all packaged python modules, and get pretty good results (in terms of stability and sustainability in the face of continuous changes in all areas..).

**Comment by frispete** [comment]
After switching my build to git master, I'm facing another **strange** issue. All tests but exactly one succeed:
```
[   32s] + PYTHONPATH=./build/lib.linux-x86_64-3.8
[   32s] + python3 -m pytest tests
[   32s] ============================= test session starts ==============================
[   32s] platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
[   32s] rootdir: /home/abuild/rpmbuild/BUILD/python-poppler-0.2.1+git20200930.d09bfc7
[   32s] collected 172 items
[   32s] 
[   33s] tests/test_destination.py ...                                            [  1%]
[   33s] tests/test_document.py ....F............................................ [ 30%]
[   33s] ..............................................                           [ 56%]
[   33s] tests/test_font.py ....                                                  [ 59%]
[   33s] tests/test_image.py .....                                                [ 62%]
[   33s] tests/test_page.py ...............                                       [ 70%]
[   33s] tests/test_pagerenderer.py ............                                  [ 77%]
[   33s] tests/test_pagetransition.py ..........................                  [ 93%]
[   33s] tests/test_rectangle.py ......                                           [ 96%]
[   33s] tests/test_toc.py ...                                                    [ 98%]
[   33s] tests/test_version.py ...                                                [100%]
[   33s] 
[   33s] =================================== FAILURES ===================================
[   33s] _____________________________ test_load_with_file ______________________________
[   33s] 
[   33s] data_path = PosixPath('/home/abuild/rpmbuild/BUILD/python-poppler-0.2.1+git20200930.d09bfc7/tests/data')
[   33s] 
[   33s]     def test_load_with_file(data_path):
[   33s]         with (data_path / "document.pdf").open("rb") as f:
[   33s]             pdf_document = document.load(f, "owner", "user")
[   33s]         if version() < (0, 46, 0):
[   33s]             assert pdf_document.author == "Charles"
[   33s]         else:
[   33s] >           assert pdf_document.author == "Charles Brunet"
[   33s] E           AssertionError: assert '' == 'Charles Brunet'
[   33s] E             - Charles Brunet
[   33s] 
[   33s] tests/test_document.py:73: AssertionError
[   33s] ----------------------------- Captured stderr call -----------------------------
[   33s] poppler/error (7622): Command token too long
[   33s] poppler/error (7750): Command token too long
[   33s] poppler/error (7878): Command token too long
[   33s] poppler/error (8006): Command token too long
[   33s] poppler/error (8134): Command token too long
[   33s] poppler/error: xref num 19 not found but needed, try to reconstruct<0a>
[   33s] poppler/error: Couldn't find trailer dictionary
[   33s] =========================== short test summary info ============================
[   33s] FAILED tests/test_document.py::test_load_with_file - AssertionError: assert '...
[   33s] ======================== 1 failed, 171 passed in 0.44s =========================
```

Running the same code from a git checkout does work properly. Puzzled. Given, that all the variations do work well, but the file argument does not, just don't make any sense to me.. Does this ring a bell for you?

**Comment by frispete** [comment]
Package on OBS updated, full [build log](https://build.opensuse.org/package/live_build_log/home:frispete:python/python-poppler/openSUSE_Tumbleweed/x86_64) still valid.

**Comment by frispete** [comment]
Must be related to the build environment: if I disable the tests, a proper rpm is built, and running the tests with that installed succeeds (even with relocated tests folder). What's so different in the build environment, that this very test fails?

**Comment by cbrunet** [comment]
The error is caused by poppler. It seems it received a corrupted buffer. I remember I saw this once, but I cannot remember why? I'm still trying to find a way to reproduce this.

**Comment by frispete** [comment]
Hi Charles, this one is driving me crazy. 

I could disable this very test easily, but experience has shown, that such things might bite later on. 

I would like to make python-poppler an important part in an internal development project (that's based on pdftotext for now).

That's my motivation to fix this.

Here's what I've done so far:
 * reduced to a minimal script
 * eliminated/fixed everything thinkable 
   * build environments lack internet (for good reasons: reproducibility)
   * python3 test may fail due to missing or wrong console encoding
   * some hidden dependencies (poppler-data in this case)
 * straced the beast down to the bones

```
import sys
import poppler
from pathlib import Path

def exit(retcode, *args):
    if args:
        print(*args, file=sys.stderr, flush = True)
    sys.exit(retcode)

try:
     pdf_file = Path(sys.argv[1])
except IndexError:
    exit('no file specified')

if not pdf_file.suffix == '.pdf':
    exit('no pdf file')

with pdf_file.open("rb") as f:
    pdf_document = poppler.document.load(f, "owner", "user")
    print('Author:', pdf_document.author)

```

**Comment by cbrunet** [comment]
I had an idea this night. Not sure if it will work... Could you try the fix-corrupted-document-buffer branch, and tell me if it helps?

**Comment by frispete** [comment]
I love your ideas at night. You made my day, Charles. Guess, a new release is in order.

Will submit this to the official openSUSE python repo, and further on to the next distribution.

**Comment by cbrunet** [comment]
Here is the explanation of the problem:

poppler load_from_data takes a pointer to data as argument. I am creating this pointer from a bytes object. However, the poppler document do not copy the buffer data, and uses it for different operations. The python bytes object was garbage collected, and the poppler document tried to access its data from a no longer valid pointer.

The solution is to keep the bytes object as member of the python document object, to keep it alive as long as the document is alive.

I will merge this in master and release a new version soon.

**Comment by frispete** [comment]
Here's the result of your hard work:

[openSUSE Leap 15.1, 15.2 and Tumbleweed with a lot of custom packages](https://build.opensuse.org/package/show/home:frispete:python/python-poppler): Poppler 0.90, Python 3.8.5
[openSUSE Tumbleweed with a few of custom packages](https://build.opensuse.org/package/show/home:frispete:Tumbleweed/python-poppler): Poppler 0.90, Python 3.8.5
[openSUSE Leap 15.1](https://build.opensuse.org/package/show/home:frispete:15.1/python-poppler): Poppler 0.62, Python 3.6.10 fails due to pathlib [incompatibilities](https://build.opensuse.org/package/live_build_log/home:frispete:15.1/python-poppler/openSUSE_Leap_15.1/x86_64)
[openSUSE Leap 15.2](https://build.opensuse.org/package/show/home:frispete:15.2/python-poppler): Poppler 0.62, Python 3.6.10 probably fails as well

Not sure, if you want to address this pathlib issue, but replacing Pythons in usual distributions is not exactly funny...

**Comment by frispete** [comment]
I haven't checked, but pathlib2 might provide a compatible interface for older Pythons?!?

**Comment by frispete** [comment]
Thanks for the explanation, Charles. The ugly part of this issue was the different garbage collector behavior. Anyway, I'm glad, you fixed it, and it definitely better to face such issues during packaging, than in a rollout somewhere handling productive data...

And the way, you dealt with these issues raised my confidence in you and your project. The code I've seen so far, was pretty nice as well. 

Thank you for the great support here!

**Comment by cbrunet** [comment]
The problem is not pathlib, it is that functools.singledispatch does not support type annotation before Python 3.7. I do not remember if there are other compatibility issues with Python 3.6.

**Comment by frispete** [comment]
All issues, including Python 3.6 compatibility, are fixed now.

Thanks again.
