### ISSUE TITLE
Installing on MacOsX Catalina

### ISSUE THREAD

**Issue by bordaigorl** [cbrunet/python-poppler#2]
I can't seem to be able to install `python-poppler` on my system (MacOS X Catalina).
I have Xcode installed with the commandline utilities (I can compile with clang).
I run `brew install poppler` with no issue, the files are correctly found at `/usr/local/opt/poppler`.
My `CFLAGS` and `CPPFLAGS` environment variables both include `-I/usr/local/opt/poppler/include`.
I manage python2/3 via `pyenv`. `pyenv version` gives me `3.8.2` as expected.

When I run `pip install python-poppler` the installation fails.
Examining the log it seems that the compiler fails to find the header files:

```
    running build_ext
    -- The C compiler identification is AppleClang 11.0.3.11030032
    -- The CXX compiler identification is AppleClang 11.0.3.11030032
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
    -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
    -- Checking for module 'poppler-cpp>=0.62.0'
    --   Found poppler-cpp, version 0.89.0
    -- Found PythonInterp: /Users/bordaigorl/.pyenv/versions/3.8.2/bin/python3.8 (found version "3.8.2")
    -- Found PythonLibs: /Users/bordaigorl/.pyenv/versions/3.8.2/lib/libpython3.8.a
    -- Performing Test HAS_CPP14_FLAG
    -- Performing Test HAS_CPP14_FLAG - Success
    -- pybind11 v2.5.0
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- LTO enabled
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /private/var/folders/jx/r7g7g23n5rb_fdycrtdl5sdw0000gn/T/pip-install-j_u40vtr/python-poppler/build/temp.macosx-10.15-x86_64-3.8
    Scanning dependencies of target font
    Scanning dependencies of target page_renderer
    [  8%] Building CXX object CMakeFiles/page_renderer.dir/src/cpp/page_renderer.cpp.o
    [  8%] Building CXX object CMakeFiles/font.dir/src/cpp/font.cpp.o
    In file included from /private/var/folders/jx/r7g7g23n5rb_fdycrtdl5sdw0000gn/T/pip-install-j_u40vtr/python-poppler/src/cpp/page_renderer.cpp:19:
    /private/var/folders/jx/r7g7g23n5rb_fdycrtdl5sdw0000gn/T/pip-install-j_u40vtr/python-poppler/src/cpp/version.h:21:10: fatal error: 'poppler/cpp/poppler-version.h' file not found
    #include <poppler/cpp/poppler-version.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

I was very confused because `clang` sees the includes just fine if run manually.
I then thought that maybe it's cmake's fault and found this:
https://gitlab.kitware.com/cmake/cmake/-/issues/19120
So I symlinked

    sudo ln -s /usr/local/include/poppler /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/poppler

and now `pip install python-poppler` works.
Is there a way to fix this without dodgy symlinks?

**Comment by cbrunet** [comment]
Did you try to set the PKG_CONFIG_PATH environment variable, as described in the *Building from Poppler sources* sections of the README?

**Comment by bordaigorl** [comment]
Yes, my `PKG_CONFIG_PATH` is `/usr/local/opt/poppler/lib/pkgconfig`.

**Comment by cbrunet** [comment]
Ok, I tried something. Could you please checkout the fix-include-paths branch, and tell me if it solves the problem?

**Comment by cbrunet** [comment]
I'm pretty sure I'm right with the fix I propose. I will merge it.

**Comment by bordaigorl** [comment]
Hi sorry for the radio silence, I may have some time to test it in the weekend.
What should I do to test it? Is it possible to just point pip at the new branch?

**Comment by cbrunet** [comment]
I just created a new release on PyPI. Therefore, you could test with a simple pip install --upgrade.

If it still doesn't work, please reopen this bug. Otherwise, I will consider it is solved.

Thank you for your help.

**Comment by bordaigorl** [comment]
It seems to be working!
Thanks a lot, great work!
