### ISSUE TITLE
Issue in installing python-poppler

### ISSUE THREAD

**Issue by tusharmakkar08-eightfold** [cbrunet/python-poppler#26]
Hey

I am trying to install python-poppler on my ubuntu machine. It gets successfully installed but when I try to import it, I see this error. 

```
>>> import poppler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/poppler/build/py-virt3/lib/python3.6/site-packages/poppler/__init__.py", line 22, in <module>
    from poppler.document import load, load_from_file, load_from_data
  File "/home/ec2-user/poppler/build/py-virt3/lib/python3.6/site-packages/poppler/document.py", line 21, in <module>
    from poppler.destination import Destination
  File "/home/ec2-user/poppler/build/py-virt3/lib/python3.6/site-packages/poppler/destination.py", line 21, in <module>
    from poppler.cpp.destination import type_enum as DestinationType  # noqa
ImportError: cannot import name 'type_enum'

```
I have installed poppler from source using instructions mentioned [here](https://cbrunet.github.io/python-poppler/installation.html#compiling-your-own-version-of-poppler). Any help would be appreciated. 

Thanks.

**Comment by cbrunet** [comment]
Its difficult to know exactly what is happening without more details. Is LD_LIBRARY_PATH correctly set? The continuous integration pipeline compiles and installs python-poppler on Ubuntu with no issues. Maybe you should use it as an example?

**Comment by cbrunet** [comment]
Do you still have an issue? Can I close this?

**Comment by tusharmakkar08-eightfold** [comment]
Since I wasn't able to debug the issue. I opened up a new machine and it started working fine. Thanks for your help.
