### ISSUE TITLE
Issue in installing python-poppler on GCP VM PyTorch/CUDA11.0.GPU

### ISSUE THREAD

**Issue by Olivier-Lakoue** [cbrunet/python-poppler#47]
Hi,

i've tryed this nice tools on my windows laptop, no pb with installation.

I want to scale and itry to install it on my GCP VM ( PyTorch:1.7/CUDA11.0.GPU ) and installation crash ...

You can find below error msg, many thanks for your help.

Bests regards, Olivier.
----------------------

Collecting python-poppler
  Using cached python-poppler-0.2.2.tar.gz (595 kB)
Building wheels for collected packages: python-poppler
  Building wheel for python-poppler (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/conda/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ar576gab/python-poppler_3308e3b17b604d49bb817e3fd73eeffe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ar576gab/python-poppler_3308e3b17b604d49bb817e3fd73eeffe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-2ut924lj
       cwd: /tmp/pip-install-ar576gab/python-poppler_3308e3b17b604d49bb817e3fd73eeffe/
  Complete output (91 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/poppler
  copying src/poppler/pagerenderer.py -> build/lib.linux-x86_64-3.7/poppler
  copying src/poppler/image.py -> build/lib.linux-x86_64-3.7/poppler
  copying src/poppler/font.py -> build/lib.linux-x86_64-3.7/poppler
  copying src/poppler/__init__.py -> build/lib.linux-x86_64-3.7/poppler
  copying src/poppler/document.py -> build/lib.linux-x86_64-3.7/poppler
  copying src/poppler/rectangle.py -> build/lib.linux-x86_64-3.7/poppler
  copying src/poppler/_version.py -> build/lib.linux-x86_64-3.7/poppler
  copying src/poppler/utilities.py -> build/lib.linux-x86_64-3.7/poppler
  copying src/poppler/embeddedfile.py -> build/lib.linux-x86_64-3.7/poppler
  copying src/poppler/destination.py -> build/lib.linux-x86_64-3.7/poppler
  copying src/poppler/pagetransition.py -> build/lib.linux-x86_64-3.7/poppler
  copying src/poppler/page.py -> build/lib.linux-x86_64-3.7/poppler
  copying src/poppler/toc.py -> build/lib.linux-x86_64-3.7/poppler
  creating build/lib.linux-x86_64-3.7/poppler/cpp
  copying src/poppler/cpp/__init__.py -> build/lib.linux-x86_64-3.7/poppler/cpp
  running egg_info
  writing src/python_poppler.egg-info/PKG-INFO
  writing dependency_links to src/python_poppler.egg-info/dependency_links.txt
  writing top-level names to src/python_poppler.egg-info/top_level.txt
  reading manifest file 'src/python_poppler.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'src/python_poppler.egg-info/SOURCES.txt'
  running build_ext
  -- The C compiler identification is GNU 8.3.0
  -- The CXX compiler identification is GNU 8.3.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /opt/conda/bin/python3.7 (found version "3.7.10")
  -- Found PythonLibs: /opt/conda/lib/libpython3.7m.so
  -- Performing Test HAS_CPP14_FLAG
  -- Performing Test HAS_CPP14_FLAG - Success
  -- pybind11 v2.5.0
  -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29")
  -- Checking for module 'poppler-cpp>=0.26.0'
  --   No package 'poppler-cpp' found
  CMake Error at /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:452 (message):
    A required package was not found
  Call Stack (most recent call first):
    /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:622 (_pkg_check_modules_internal)
    CMakeLists.txt:14 (pkg_check_modules)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-ar576gab/python-poppler_3308e3b17b604d49bb817e3fd73eeffe/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".

**Comment by frispete** [comment]
> -- No package 'poppler-cpp' found

Have you tried to provide dependencies?

**Comment by Olivier-Lakoue** [comment]
Hi,

I've made as indicated in the doc :

_Installing from PyPI is the easiest way to install python-poppler. Be sure to have all the requirements installed. Ideally, you should install the package inside a Python virtual environment._

==> ! pip install python-poppler from my Notebook running on the VM.

I've forget something ?

Thanks.

**Comment by Olivier-Lakoue** [comment]
Hi,

I've made as indicated in the doc :
Installing from PyPI is the easiest way to install python-poppler. Be sure to have all the requirements installed. Ideally, you should install the package inside a Python virtual environment.

==> ! pip install python-poppler from my Notebook running on the VM.

I've forget something ? how to install independently the dependecies ?

Thanks.

**Comment by Olivier-Lakoue** [comment]
target is to deploy it on a GCloud function.

Do you have a simple script to install included dependecies ?

Thanks.

**Comment by cbrunet** [comment]
cmake doesn't find the poppler lib. Did you installed it? If it is not in a standard location, you may need to adjust the LD_LIBRARY_PATH env var as well.

**Comment by mara004** [comment]
If the Linux that runs in your VM is something Debian-based, you can probably do:
```bash
$ sudo apt install libpoppler-dev
```

**Comment by Olivier-Lakoue** [comment]
Hi All,

Thanks to mara004 and all for your help.

I've installed dependecies one per one and it's ok now.
$ sudo apt install libpoppler-dev

i think you'd better improve install process because your package is very usefull :)

Thanks for your help, i close the issue.
