### ISSUE TITLE
Suppressing error messages

### ISSUE THREAD

**Issue by gollux** [cbrunet/python-poppler#49]
If the document is broken, Poppler spews error messages to stderr, which is messy (especially if I am processing multiple documents in parallel).

It would be great to have a possibility of silencing error messages (by setting Poppler's `globalParams`), or even better by providing a Python callback for reporting errors.

**Comment by cbrunet** [comment]
Yes, it could be a great addition. I don't really have time to look at it right now. A Pull Request would be appreciated, or at least a sample pdf document that could be used to write tests.

Meanwhile, you could use contextlib.redirect_stderr (https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stderr) to capture outputs to stderr.

**Comment by bzamecnik** [comment]
@cbrunet @gollux Implemented in https://github.com/cbrunet/python-poppler/pull/61.

**Comment by cbrunet** [comment]
Fixed by #61
