### ISSUE TITLE
Exceptions in `page.py` after poppler update

### ISSUE THREAD

**Issue by mara004** [cbrunet/python-poppler#51]
After applying distribution updates to poppler on KDE Neon User, I got `AttributeError` exceptions when importing python-poppler, caused by the following code passages:
https://github.com/cbrunet/python-poppler/blob/33d36b1b697f77d7a29ceb589ed159311693ef6c/src/poppler/page.py#L27-L28
https://github.com/cbrunet/python-poppler/blob/33d36b1b697f77d7a29ceb589ed159311693ef6c/src/poppler/page.py#L77-L78
Removing these blocks fixed the issue for me. I installed python-poppler from source. The distribution-provided poppler package is at version `22.04.0`.

**Comment by cbrunet** [comment]
Did you recompiled python-poppler after updating the cpp-poppler library? It looks like poppler reports the right version, but the enum are now available in the bindings.

**Comment by mara004** [comment]
Oh, right, I forgot to recompile.
