### ISSUE TITLE
Tutorial on using this module to convert PDF to image

### ISSUE THREAD

**Issue by farooqkz** [cbrunet/python-poppler#54]
Hello.
I've written a small guide [here on my website](https://far.chickenkiller.com/computer/converting-pdf-to-image-in-python-the-right-way/) and I would be happy if it's of some use for the others. Maybe include it in the docs or README.md or somewhere?

**Comment by farooqkz** [comment]
@cbrunet hello?

**Comment by cbrunet** [comment]
Thank you for the blog post. It looks great. Why the `>>> renderer.` line in the last example? Is it an error?

However, I think everything there is already in the official documentation. But I will keep it in mind if someday I decide to compile a list of articles about python-poppler, or something like that.

**Comment by farooqkz** [comment]
As you wish :)
