### ISSUE TITLE
Method to read image data encoded instead of saving it in a file

### ISSUE THREAD

**Issue by farooqkz** [cbrunet/python-poppler#56]
Hello
I am writing an application which requires getting PNG bytestring of an `Image` directly rather than saving it in a file.
I think it would be nice to have a method for `Image` class to have this done.

**Comment by cbrunet** [comment]
You should be able to access image data using `Image.data` property.

**Comment by farooqkz** [comment]
But it is raw in RGBA or something and not PNG right?

**Comment by cbrunet** [comment]
Yes is it probably raw data. What would be the use of a PNG bytestring?

You could probably use opencv or PIL to convert the data, if this is what you need. Image.save function is provided by poppler-cpp library. It is not possible to intercept data using it.

**Comment by farooqkz** [comment]
I mean why not add a method similar to `Image.save` but for getting raw encoded PNG(or whatever supported format) data?

**Comment by cbrunet** [comment]
Because poppler-cpp does not provide such a method. And because I don't want to add a dependency to python-poppler just for that.
