### ISSUE TITLE
ERROR!!! [HELP WANTED]

### ISSUE THREAD

**Issue by athrvvvv** [cbrunet/python-poppler#57]
#### Iam currently working on a PDF viewer software with the help of [Python-Poppler](https://github.com/cbrunet/python-poppler) but unfortunately I ran into <strong>ERROR</strong> while installing the package. 

![error1](https://user-images.githubusercontent.com/98272709/163760714-12fb7133-5c4c-4911-b24c-9f5e321b6095.png)
![error2](https://user-images.githubusercontent.com/98272709/163760723-5d67f1c3-9883-4a24-8df7-20904ab2746c.png)

#### What can I do for solving this ERROR????

**Comment by pudo** [comment]
You are probably missing some dependencies. The minimum I've been able to build this with has been (on debian/ubuntu): 

```
apt install libpoppler-cpp-dev libpoppler-dev cmake python3-pkgconfig python3-pip
```

If you figure out the windows equivalents, that may be a cool docs PR to contribute :)

**Comment by cbrunet** [comment]
python-poppler does not support Windows yet. Duplicates #9.
