### ISSUE TITLE
not able to install in windows

### ISSUE THREAD

**Issue by loooong** [cbrunet/python-poppler#60]
1. command "pip install python-poppler " in windows 11. The system cannot find poppler-cpp.
![image](https://user-images.githubusercontent.com/8617946/174475785-9f487145-dddd-46b4-bb5d-8849064e61a7.png)

2.  But I have "poppler-cpp.lib" in this dir (after run "conda install -c conda-forge poppler"), whose path is already included in the environmental variable.
<img width="925" alt="image" src="https://user-images.githubusercontent.com/8617946/174476389-41a7d638-99ff-41db-9996-19fe0b16eb28.png">

**Comment by loooong** [comment]
call for help ~~

**Comment by cbrunet** [comment]
We do not support Windows yet.

The cmake script uses pkgconfig to find the required libs. Therefore, it needs a special configuration file (poppler-cpp.pc) telling where to find header files and libraries. I'm not sure how it works on Windows. Having poppler-cpp.lib is not sufficient.

**Comment by cbrunet** [comment]
Duplicates #9

**Comment by PasaOpasen** [comment]
> We do not support Windows yet.
> 
> The cmake script uses pkgconfig to find the required libs. Therefore, it needs a special configuration file (poppler-cpp.pc) telling where to find header files and libraries. I'm not sure how it works on Windows. Having poppler-cpp.lib is not sufficient.

but it works on some old versions??
