### ISSUE TITLE
python-poppler package installation via poetry gives error

### ISSUE THREAD

**Issue by rock321987** [cbrunet/python-poppler#71]
Details of the issue are mentioned here: https://github.com/python-poetry/poetry/issues/7653

**Comment by cbrunet** [comment]
From the traceback you give, there seems to be a problem with cmake. However, I don't see this problem on my computer.

I'm currently rewriting the whole build process using meson. You could try it from the pull request branch, or wait a few days until I prepare a new release...

**Comment by rock321987** [comment]
The branch works fine.. Tried with

`poetry add git+https://github.com/cbrunet/python-poppler.git#meson-build-system`

**Comment by cbrunet** [comment]
Fixed by #70. Should work with the new 0.4.0 release.

**Comment by alita-moore** [comment]
having this issue with 0.4.1 from pypi `poetry add python-poppler`
