### ISSUE TITLE
When python projects like Facebook's detectron2 use poppler-utils, what is the difference between apt-get install poppler-utils and pip install python-poppler?

### ISSUE THREAD

**Issue by codingbutstillalive** [cbrunet/python-poppler#79]
Maybe this is more of a general question. The same would also apply to libmagic-dev or tesseract-ocr vs. pytesseract. I hope to find some answer here.

**Comment by cbrunet** [comment]
poppler-utils and python-poppler are two different things. poppler-utils are utilities to manipulate pdf documents using the poppler library. python-poppler is a python binding allowing to use the poppler library in a python application.

poppler itself is divided into three different frontends: poppler-cpp, popplet-qt5 and poppler-qt6, and poppler-glib. python-poppler uses poppler-cpp, which has less dependencies, but also less capabilities. 

I dont know how detectron2 uses poppler, but it is possible it uses the glib bindings, which are available using python, or that it simply calls executables from poppler-utils, using subprocesses.
