### ISSUE TITLE
[Enhancement]: Provide a way to access images embedded in a PDF

### ISSUE THREAD

**Issue by fake-name** [cbrunet/python-poppler#8]
I'm trying to extract both the text *and* images in a PDF, ideally without recompressing or converting the image formats if possible.

This is pretty trivial to do with `pdfminer` or `PyPDF2`, but they're cripplingly slow for extracting text (A PDF which poppler/python-poppler processes in \~1-2 seconds takes 200+ seconds\~). On the other hand, there doesn't seem to be *any* way to get images through python-poppler.

Now, [poppler provides a `pdfimages` utility that uses poppler to extract images](https://manpages.debian.org/testing/poppler-utils/pdfimages.1.en.html), but it looks like it's [pretty annoying to do internally](https://github.com/freedesktop/poppler/blob/master/utils/pdfimages.cc#L187).

AFICT, basically the way the `pdfimages` extracts images is to provide a custom page rendering device (`ImageOutputDev`), which rather then doing actual compositing when rendering a page just ignores all draw commands other then `drawImage_xxx()` calls, and instead just saves the data passed to the draw image calls. 

I think it'd be pretty easy to tweak `ImageOutputDev.cc` to instead write images to memory, and then provide a python call that returns the images as bytes, but I don't have a great idea how to start integrating this with the wrapper bits.

**Comment by cbrunet** [comment]
I'm not sure about this one. poppler is special, because it provides several different interfaces (cpp, qt, glib) that offer different functionalities, and a few utility applications, based directly on the internals of poppler. pdfimages is one of them. python-poppler is based on the cpp backend of poppler. Therefore, the best way to have this functionality would be to have it upstream, in poppler-cpp. Then I would provide the python binding.

**Comment by fake-name** [comment]
Basically, my interest in this library is contingent on being able to use it for what I need to do, which in this case is being able to extract both text and image resources. 

I'm not opposed to trying to upstream any changes (from what I'm thinking, this would basically be a modified version of `ImageOutputDev.cc` in poppler, but my priority here is getting a working library that does what I need. This whole thing is just one part of *another* project I'm trying to do, which is format-agnostic ebook deduplication, of which PDF ingestion is just one format.

Currently, I'd be ok with just running a vendored version, so would you be OK with having the relevant bits be in python-poppler until they when/if they get upstreamed? If nothing else, it provides a handy way to do testing without having to write a bunch of C++ test harnesses.

**Comment by fake-name** [comment]
Hahahaha: https://gitlab.freedesktop.org/poppler/poppler/-/merge_requests/349

**Comment by cbrunet** [comment]
I'm closing this, as it is not something I can do in python-poppler. I will implement it when it will be available in poppler-cpp.

**Comment by fake-name** [comment]
Yeah, I'm following up upstream. Sorry!
